version: "3.7"

services:
    wiki:
        stdin_open: true
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        image: rajacsp/wiki:latest
        container_name: wiki
        environment:
            - DEBUG=True
        ports:
            - 8000:8000
            - 3000:3000
        entrypoint:
            - /bin/bash
            - -c
            - |
                sleep infinity
                # git clone https://github.com/rajacsp/rajacsp.github.io.git
                # cd rajacsp.github.io/.layouts
                # npm i
                # npm start
                # npm run start --host 0.0.0.0  # not working
                # npm run build
                # cd ..
                # git checkout -b gh-pages
                # git add .layouts/public -f
                # git config --global user.email "rajacsp@gmail.com"
                # git commit -m "added gh-pages"
                # git push origin `git subtree split --prefix .layouts/public gh-pages`:gh-pages --force
                # git push https://rajacsp:xxx@github.com/rajacsp/rajacsp.github.io.git `git subtree split --prefix .layouts/public gh-pages`:gh-pages --force

                # git add .layouts/public -f
                # git branch gh-pages
                # git subtree split --prefix '.layouts/public' -b gh-pages
                # git push -f https://rajacsp:xxx@github.com/rajacsp/rajacsp.github.io.git gh-pages:gh-pages

                # git subtree push --prefix .layouts/public origin gh-pages
                # git subtree push --prefix .layouts/public https://rajacsp:xxx@github.com/rajacsp/rajacsp.github.io.git gh-pages

                # running docusaurus locally
                # npm ci
                # npm start

        volumes:
            - .:/app/
